"""empty message

Revision ID: 006f60b15cc4
Revises: dbc2ed59a4b8
Create Date: 2024-01-09 13:35:57.564546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006f60b15cc4'
down_revision = 'dbc2ed59a4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_ip', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.drop_column('dev_ip')

    # ### end Alembic commands ###
