"""empty message

Revision ID: 039cad0aec54
Revises: 5b8b562466f7
Create Date: 2024-03-05 14:57:13.258986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '039cad0aec54'
down_revision = '5b8b562466f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('menu_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('menu_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               nullable=False)

    # ### end Alembic commands ###
