"""empty message

Revision ID: 0ddb97b8234d
Revises: 006f60b15cc4
Create Date: 2024-01-29 10:40:14.235411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ddb97b8234d'
down_revision = '006f60b15cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_build_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jks_job_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('k8s_build_id_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'k8s_job', ['jks_job_id'], ['id'])
        batch_op.drop_column('k8s_job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_build_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k8s_job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('k8s_build_id_ibfk_1', 'k8s_job', ['k8s_job_id'], ['id'])
        batch_op.drop_column('jks_job_id')

    # ### end Alembic commands ###
