"""empty message

Revision ID: 172b537ba4fc
Revises: 9a5747bbadb2
Create Date: 2023-12-19 09:37:32.601204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '172b537ba4fc'
down_revision = '9a5747bbadb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=32), nullable=False))
        batch_op.drop_index('rolename')
        batch_op.create_unique_constraint(None, ['role_name'])
        batch_op.drop_column('rolename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rolename', mysql.VARCHAR(collation='utf8mb4_bin', length=32), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('rolename', ['rolename'], unique=False)
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
