"""empty message

Revision ID: 1d9efcfc3227
Revises: ddefce938f3c
Create Date: 2023-07-24 10:35:44.421817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9efcfc3227'
down_revision = 'ddefce938f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignee_create_time'), ['create_time'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assignee', ['assignee_id'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assignee', ['assignee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assignee_id')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assignee_id')

    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignee_create_time'))

    op.drop_table('assignee')
    # ### end Alembic commands ###
