"""empty message

Revision ID: 42000d89bd71
Revises: a26f2c71d846
Create Date: 2024-03-13 09:26:30.193168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42000d89bd71'
down_revision = 'a26f2c71d846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_component', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('route_component')

    # ### end Alembic commands ###
