"""empty message

Revision ID: 4563f027dc39
Revises: e3b97c628862
Create Date: 2023-08-17 09:58:10.508252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4563f027dc39'
down_revision = 'e3b97c628862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index('ix_search_history_create_time')

    op.drop_table('search_history')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('comment')

    op.create_table('search_history',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('keyword', mysql.VARCHAR(collation='utf8mb4_bin', length=64), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='search_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('ix_search_history_create_time', ['create_time'], unique=False)

    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comment', mysql.TEXT(collation='utf8mb4_bin'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('attachment_url', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('assignee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['assignee.id'], name='feedback_ibfk_3'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name='feedback_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='feedback_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
