"""empty message

Revision ID: 4cbfa4688d37
Revises: b26e93f385c0
Create Date: 2024-01-02 15:38:16.546310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbfa4688d37'
down_revision = 'b26e93f385c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenkins_k8s', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenkins_k8s', schema=None) as batch_op:
        batch_op.drop_column('job_path')

    # ### end Alembic commands ###
