"""empty message

Revision ID: 523bb38a03f7
Revises: 01dda0bf8a27
Create Date: 2023-12-21 17:31:58.532641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523bb38a03f7'
down_revision = '01dda0bf8a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPic', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('userPic')

    # ### end Alembic commands ###
