"""empty message

Revision ID: 5b8b562466f7
Revises: 71c1baaa2107
Create Date: 2024-03-05 11:26:34.991145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8b562466f7'
down_revision = '71c1baaa2107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.String(length=32), nullable=False),
    sa.Column('menu_path', sa.String(length=32), nullable=False),
    sa.Column('menu_type', sa.Enum('directory', 'menu', 'button'), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('parentName', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_name'),
    sa.UniqueConstraint('menu_path')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_create_time'), ['create_time'], unique=False)

    op.create_table('role_to_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_to_menu')
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_create_time'))

    op.drop_table('menu')
    # ### end Alembic commands ###
