"""empty message

Revision ID: 9857a64bec54
Revises: 4563f027dc39
Create Date: 2023-08-17 15:19:14.502317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9857a64bec54'
down_revision = '4563f027dc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['assignee.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=16), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.TEXT(collation='utf8mb4_bin'), nullable=True))

    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.drop_column('department')

    op.drop_table('feedback')
    # ### end Alembic commands ###
