"""empty message

Revision ID: ae446e9461d2
Revises: 4cbfa4688d37
Create Date: 2024-01-03 13:18:00.532391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae446e9461d2'
down_revision = '4cbfa4688d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_path', sa.String(length=512), nullable=True),
    sa.Column('job_info', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8s_build_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_build_id', sa.Integer(), nullable=True),
    sa.Column('k8s_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['k8s_job_id'], ['k8s_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jenkins_k8s')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenkins_k8s',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('job_name', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False),
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('job_info', mysql.TEXT(collation='utf8mb4_bin'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('job_path', mysql.VARCHAR(collation='utf8mb4_bin', length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('k8s_build_id')
    op.drop_table('k8s_job')
    # ### end Alembic commands ###
