"""empty message

Revision ID: b73bd2d57791
Revises: 4245e33dc067
Create Date: 2024-02-04 15:39:49.968797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73bd2d57791'
down_revision = '4245e33dc067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastgray_build_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lastgray_build_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lastprod_build_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lastprod_build_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.drop_column('lastprod_build_time')
        batch_op.drop_column('lastprod_build_id')
        batch_op.drop_column('lastgray_build_time')
        batch_op.drop_column('lastgray_build_id')

    # ### end Alembic commands ###
