"""empty message

Revision ID: d61a6b8c7ade
Revises: 0ddb97b8234d
Create Date: 2024-01-29 10:49:46.167146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd61a6b8c7ade'
down_revision = '0ddb97b8234d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_build_id', schema=None) as batch_op:
        batch_op.drop_column('k8s_job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_build_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k8s_job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
