"""empty message

Revision ID: dbc2ed59a4b8
Revises: 8798d47d8ea3
Create Date: 2024-01-09 13:35:14.976216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc2ed59a4b8'
down_revision = '8798d47d8ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_ip', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('git_address', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['job_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('git_address')
        batch_op.drop_column('test_ip')

    # ### end Alembic commands ###
