"""empty message

Revision ID: eac808e5b4bc
Revises: 903784127da7
Create Date: 2023-11-27 16:36:12.585239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eac808e5b4bc'
down_revision = '903784127da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('attachment_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('attachment_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
