"""empty message

Revision ID: ebe3ffa70daf
Revises: 172b537ba4fc
Create Date: 2023-12-19 09:46:51.838853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebe3ffa70daf'
down_revision = '172b537ba4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               type_=sa.Enum('超级管理员', '普通用户'),
               existing_nullable=False)
        batch_op.drop_index('role_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('role_name', ['role_name'], unique=False)
        batch_op.alter_column('role_name',
               existing_type=sa.Enum('超级管理员', '普通用户'),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
