"""empty message

Revision ID: f546176edc06
Revises: 517a60bee63b
Create Date: 2023-08-17 16:33:53.006097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f546176edc06'
down_revision = '517a60bee63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_ibfk_1', type_='foreignkey')
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('feedback_ibfk_1', 'assignee', ['assignee_id'], ['id'])

    # ### end Alembic commands ###
